apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesysteam
  accessModes:
    - ReadWriteOnce
  hostpath:
    path: /check
    type: DirectoryOrCreate